name: Build All

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions: {}

jobs:
  build-msbuild:
    permissions:
      id-token: 'write'
      attestations: 'write'
    uses: ./.github/workflows/build-msbuild.yaml

  release:
    if: ${{ github.ref_type == 'tag' }}
    needs: build-msbuild
    runs-on: ubuntu-latest

    permissions:
      contents: 'write'

    steps:
      - name: Fetch Builds
        uses: actions/download-artifact@v8.0.1
        with:
          pattern: gm-apclientpp-*.zip
          skip-decompress: true  # should not be compressed

      - name: Set env
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64  # v3.0.3
        with:
          draft: true
          name: gm-apclientpp ${{ env.RELEASE_TAG }}
          files: gm-apclientpp-*.zip
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
